import type { Elements } from "@clerk/types";

export const clerkElements = undefined;

export const clerkElementsFuture: Elements = {
  card: "bg-background border-accent",
  logoBox: "",
  logoImage: "",
  header: "text-primary",
  headerTitle: "text-primary",
  headerSubtitle: "text-secondary-foreground",
  headerBackRow: "text-primary-foreground hovact:text-primary",
  headerBackLink: "text-primary-foreground hovact:text-primary",
  headerBackIcon: "fill-primary",
  main: "",
  footerAction: "text-primary hovact:text-primary-foreground",
  footerActionText: "text-foreground",
  footerActionLink: "text-foreground hovact:text-primary decoration-none",
  footerPages: "",
  footerPagesLink: "text-foreground hovact:text-primary decoration-none",
  socialButtons: "",
  socialButtonsIconButton:
    "bg-primary text-primary-foreground hovact:bg-primary-foreground hovact:text-primary",
  socialButtonsBlockButton:
    "bg-secondary text-secondary-foreground hovact:bg-accent",
  socialButtonsBlockButtonText: "text-secondary-foreground",
  socialButtonsBlockButtonArrow: "fill-secondary-foreground",
  socialButtonsProviderIcon: "",
  enterpriseButtonsProviderIcon: "",
  alternativeMethods: "",
  alternativeMethodsBlockButton:
    "bg-accent text-accent-foreground hovact:bg-secondary",
  alternativeMethodsBlockButtonText:
    "text-accent-foreground hovact:text-secondary",
  alternativeMethodsBlockButtonArrow:
    "fill-accent-foreground hovact:fill-secondary",
  otpCodeBox: "",
  otpCodeHeader: "",
  otpCodeHeaderTitle: "text-primary",
  otpCodeHeaderSubtitle: "text-secondary-foreground",
  otpCodeField: "",
  otpCodeFieldInputs: "border-primary focus:border-primary-foreground",
  otpCodeFieldInput: "bg-background text-foreground",
  otpCodeFieldErrorText: "text-destructive",
  dividerRow: "",
  dividerText: "text-foreground",
  dividerLine: "border-accent",
  formHeader: "",
  formHeaderTitle: "text-primary",
  formHeaderSubtitle: "text-secondary-foreground",
  formResendCodeLink: "text-primary hovact:text-primary-foreground",
  verificationLinkStatusBox: "",
  verificationLinkStatusIconBox: "",
  verificationLinkStatusIcon: "",
  verificationLinkStatusText: "",
  form: "",
  formFieldRow: "",
  formField: "border-accent focus:border-primary",
  formFieldLabelRow: "",
  formFieldLabel: "text-foreground",
  formFieldRadioGroup: "",
  formFieldRadioGroupItem: "",
  formFieldRadioInput: "",
  formFieldRadioLabel: "text-foreground",
  formFieldRadioLabelTitle: "text-foreground",
  formFieldRadioLabelDescription: "text-secondary-foreground",
  formFieldAction: "text-primary hovact:text-primary-foreground",
  formFieldInput:
    "bg-background text-foreground placeholder:text-secondary-foreground",
  formFieldErrorText: "text-destructive",
  formFieldWarningText: "text-destructive",
  formFieldSuccessText: "text-primary",
  formFieldInfoText: "text-secondary-foreground",
  formFieldDirectionsText: "text-secondary-foreground",
  formFieldHintText: "text-secondary-foreground",
  formButtonRow: "",
  formButtonPrimary:
    "bg-primary text-primary-foreground hovact:bg-primary-foreground hovact:text-primary",
  formButtonReset: "text-secondary-foreground hovact:text-accent",
  formFieldInputGroup: "",
  formFieldInputShowPasswordButton:
    "text-primary-foreground hovact:text-primary",
  formFieldInputShowPasswordIcon: "fill-primary-foreground hovact:fill-primary",
  formFieldInputCopyToClipboardButton:
    "text-primary-foreground hovact:text-primary",
  formFieldInputCopyToClipboardIcon:
    "fill-primary-foreground hovact:fill-primary",
  phoneInputBox: "border-accent focus-within:border-primary",
  formInputGroup: "bg-background",
  avatarBox: "",
  avatarImage: "",
  avatarImageActions: "text-foreground",
  avatarImageActionsUpload:
    "bg-primary text-primary-foreground hovact:bg-primary-foreground hovact:text-primary",
  avatarImageActionsRemove:
    "bg-destructive text-destructive-foreground hovact:bg-destructive-foreground hovact:text-destructive",
  userButtonBox: "",
  userButtonOuterIdentifier: "text-foreground",
  userButtonTrigger: "bg-accent text-accent-foreground hovact:bg-secondary",
  userButtonAvatarBox: "",
  userButtonAvatarImage: "",
  userButtonPopoverRootBox: "bg-background",
  userButtonPopoverCard: "border-accent",
  userButtonPopoverMain: "",
  userButtonPopoverUserPreview: "",
  userButtonPopoverActions: "text-foreground",
  userButtonPopoverActionButton: "text-primary hovact:text-primary-foreground",
  userButtonPopoverActionButtonIconBox: "",
  userButtonPopoverActionButtonIcon: "fill-primary",
  userButtonPopoverActionButtonText: "text-foreground",
  userButtonPopoverFooter: "bg-accent",
  userButtonPopoverFooterPages: "",
  userButtonPopoverFooterPagesLink:
    "text-secondary-foreground hovact:text-primary",
  userPreview: "bg-background",
  userPreviewAvatarContainer: "",
  userPreviewAvatarBox: "",
  userPreviewAvatarImage: "",
  userPreviewTextContainer: "text-foreground",
  userPreviewMainIdentifier: "text-primary",
  userPreviewSecondaryIdentifier: "text-secondary-foreground",
  identityPreview: "bg-accent",
  identityPreviewAvatarBox: "",
  identityPreviewAvatarImage: "",
  identityPreviewText: "text-foreground",
  identityPreviewEditButton: "text-primary hovact:text-primary-foreground",
  identityPreviewEditButtonIcon: "fill-primary",
  alert: "bg-destructive text-destructive-foreground",
  alertIcon: "fill-destructive-foreground",
  alertText: "text-destructive-foreground",
  alertTextContainer: "",
  tagInputContainer: "border-accent",
  tagPillIcon: "fill-accent-foreground",
  tagPillContainer: "bg-accent text-accent-foreground",
  tabPanel: "",
  tabButton: "text-foreground hovact:bg-accent",
  tabListContainer: "",
  tableHead: "bg-accent text-accent-foreground",
  paginationButton:
    "text-primary hovact:bg-primary hovact:text-primary-foreground",
  paginationRowText: "text-secondary-foreground",
  selectButton: "bg-background text-foreground border-accent",
  selectSearchInput: "text-foreground placeholder:text-secondary-foreground",
  selectButtonIcon: "fill-foreground",
  selectOptionsContainer: "bg-background border-accent",
  selectOption: "text-foreground hovact:bg-accent",
  menuButton: "text-foreground hovact:bg-accent",
  menuList: "bg-background",
  menuItem: "text-foreground hovact:bg-accent",
  loader: "",
  loaderIcon: "fill-primary",
  modalBackdrop: "bg-background/50",
  modalContent: "bg-background border-accent",
  modalCloseButton: "text-foreground hovact:text-primary",
  profileSection: "bg-background",
  profileSectionTitle: "text-primary",
  profileSectionTitleText: "text-primary",
  profileSectionSubtitle: "text-secondary-foreground",
  profileSectionSubtitleText: "text-secondary-foreground",
  profileSectionContent: "",
  profileSectionPrimaryButton:
    "bg-primary text-primary-foreground hovact:bg-primary-foreground hovact:text-primary",
  profilePage: "bg-background",
  formattedPhoneNumber: "",
  formattedPhoneNumberFlag: "",
  formattedPhoneNumberText: "text-foreground",
  breadcrumbs: "",
  breadcrumbsItems: "",
  breadcrumbsItemBox: "text-secondary-foreground",
  breadcrumbsItem: "text-primary hovact:text-primary-foreground",
  breadcrumbsItemIcon: "fill-primary",
  breadcrumbsItemDivider: "text-secondary-foreground",
  scrollBox: "bg-background",
  navbar: "bg-background",
  navbarButtons: "text-foreground hovact:bg-accent",
  navbarButton: "text-foreground hovact:bg-accent",
  navbarButtonIcon: "fill-foreground hovact:fill-accent",
  navbarMobileMenuRow: "bg-accent",
  navbarMobileMenuButton: "text-accent-foreground hovact:text-primary",
  navbarMobileMenuButtonIcon: "fill-accent-foreground hovact:fill-primary",
  pageScrollBox: "bg-background",
  page: "bg-background",
  pageHeader: "bg-accent text-accent-foreground",
  activeDevice: "",
  activeDeviceListItem: "",
  activeDeviceIcon: "fill-primary",
  impersonationFab:
    "bg-primary text-primary-foreground hovact:bg-primary-foreground hovact:text-primary",
  impersonationFabIcon: "fill-primary-foreground",
  impersonationFabIconContainer: "",
  impersonationFabTitle: "text-primary-foreground",
  impersonationFabActionLink: "text-primary hovact:text-primary-foreground",
  fileDropAreaOuterBox: "border-accent",
  fileDropAreaBox: "bg-background",
  fileDropAreaIconBox: "",
  fileDropAreaIcon: "fill-accent",
  fileDropAreaHint: "text-secondary-foreground",
  fileDropAreaButtonPrimary:
    "bg-primary text-primary-foreground hovact:bg-primary-foreground hovact:text-primary",
  fileDropAreaFooterHint: "text-secondary-foreground",
  invitationsSentIconBox: "",
  invitationsSentIcon: "fill-primary",
  accordionTriggerButton: "text-foreground hovact:bg-accent",
  accordionContent: "bg-background",
  qrCodeRow: "",
  qrCodeContainer: "bg-background",
  badge: "bg-primary text-primary-foreground",
  notificationBadge: "bg-destructive text-destructive-foreground",
  button:
    "bg-primary text-primary-foreground hovact:bg-primary-foreground hovact:text-primary",
  providerIcon: "",
};
