import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton,
} from "@clerk/nextjs";
import { dark } from "@clerk/themes";
import "@/styles/globals.css";
import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  crudPoll,
  children,
}: {
  crudPoll: React.ReactNode;
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <ClerkProvider appearance={{ baseTheme: dark }}>
        <body className={`pt-16 font-sans ${inter.variable}`}>
          <Header />
          {crudPoll}
          {children}
        </body>
      </ClerkProvider>
    </html>
  );
}

function Header() {
  return (
    <header className="fixed left-0 top-0 flex w-full justify-between p-4">
      <Link href="/">Poll</Link>

      <SignedIn>
        <div className="flex flex-row items-center gap-4">
          <Link href="/">Home</Link>
          <Link href="/create-poll">Create Poll</Link>
          <div className="h-8 w-8">
            <UserButton />
          </div>
        </div>
      </SignedIn>

      <SignedOut>
        <SignInButton />
      </SignedOut>
    </header>
  );
}
